/**
 * AI-generation disclosure (Requirements 16.5, 16.6, 16.13, 13.7, 33.14).
 *
 * `services/moderation/disclosure-port.ts` named the three obligations and said
 * task 8.3 owns the mapping and the wording. This is that mapping and that wording, and it is
 * one module because the four clauses are the same statement made in four places:
 *
 * | Clause | Where |
 * |---|---|
 * | 16.5 | the detail screen and the public page |
 * | 16.13 | the same two, for `dialogue` |
 * | 16.6 | the stored audio, as an inaudible mark |
 * | 13.7 | the downloaded file's metadata tag |
 *
 * A second table anywhere is a way for the public page to say something the download does not.
 *
 * ### Why the labels live in the domain and not in the components
 *
 * Requirement 16.5 is satisfied by a label being *present*, and a component is where a label
 * quietly stops being present — a refactor drops a `<span>`, the tests still pass because they
 * assert on the data, and the disclosure is gone. Here it is a value: `DISCLOSURE_LABELS` is
 * total over `DisclosureObligation`, so adding an obligation without wording it is a type
 * error, and `test/unit/disclosure/ai-disclosure.test.ts` asserts the screens render what this
 * says rather than words of their own.
 *
 * ### The watermark identifier
 *
 * Requirement 33.14 makes provenance hold *both* the watermark information and the AI marking,
 * as an invariant. `AssetProvenance.aiGenerated` is the second; `watermarkId` is the first, and
 * it is required rather than optional for the same reason — an invariant with an optional field
 * is a convention. The identifier names the scheme version that marked the audio, because that
 * is what a later detection can be checked against: `dsp/.../watermark.py` reports which
 * version's carrier it found, and the two have to be comparable.
 */

import type { AssetKind } from '../asset-kind';

/** Requirements 16.5, 16.6, 16.13 — the same three names the port declares. */
export const DISCLOSURE_OBLIGATIONS = [
  'ai_generated_label',
  'inaudible_watermark',
  'synthetic_voice_label',
] as const;

export type DisclosureObligation = (typeof DISCLOSURE_OBLIGATIONS)[number];

/**
 * What each obligation says, in the language of the product.
 *
 * `Record` rather than a lookup with a fallback: a missing entry is a compile error, and the
 * failure this prevents — an obligation that is carried, checked, and then rendered as an empty
 * string — is exactly the one that passes every test that asserts on the obligation list.
 */
export const DISCLOSURE_LABELS: Readonly<Record<DisclosureObligation, string>> = {
  ai_generated_label: 'AI 생성',
  synthetic_voice_label: '합성 음성',
  // Not rendered on a screen — it is a property of the audio — but worded, because the
  // provenance export of Requirement 33.15 is read by people.
  inaudible_watermark: 'AI 생성 워터마크 포함',
};

/** Requirement 16.13's kind, as a value rather than a condition spelled out at each site. */
export const SYNTHETIC_VOICE_ASSET_KINDS: readonly AssetKind[] = ['dialogue'];

/**
 * Requirement 13.7's metadata tag.
 *
 * One string, in the `comment` field the DSP layer offers on all four download formats. It is
 * deliberately readable rather than a machine token: a listener who opens the file in a player
 * is who this clause protects, and `ai_generated=true` tells them nothing.
 */
export const AI_GENERATED_TAG_FIELD = 'comment';
export const AI_GENERATED_TAG_VALUE =
  'AI generated by MusicStudio — 이 오디오는 AI로 생성되었습니다.';

/**
 * The obligations that apply to an asset.
 *
 * Every asset carries the first two: Requirement 16.5 says 모든 Audio_Asset and 16.6 says
 * 오디오가 저장되면, neither with an exception for a kind. `dialogue` adds the third.
 *
 * Ordered rather than a set, so the screens of Requirement 16.5 and 16.13 present the two
 * labels in the same order every time and on every route.
 */
export function disclosuresFor(assetKind: AssetKind): readonly DisclosureObligation[] {
  const obligations: DisclosureObligation[] = ['ai_generated_label', 'inaudible_watermark'];
  if (SYNTHETIC_VOICE_ASSET_KINDS.includes(assetKind)) {
    obligations.push('synthetic_voice_label');
  }
  return obligations;
}

/** The obligations that are *shown* — 16.5 and 16.13 are screen clauses, 16.6 is not. */
export function visibleDisclosuresFor(assetKind: AssetKind): readonly DisclosureObligation[] {
  return disclosuresFor(assetKind).filter((obligation) => obligation !== 'inaudible_watermark');
}

/** The label a screen renders for an obligation. */
export function disclosureLabel(obligation: DisclosureObligation): string {
  return DISCLOSURE_LABELS[obligation];
}

/**
 * The watermark identifier stored in provenance (Requirement 33.14).
 *
 * `ms-wm-v<version>`, so a detection reporting version 1 is checkable against a record claiming
 * `ms-wm-v1` by comparing values rather than by parsing prose. The prefix is there because the
 * field is read alongside engine and licence identifiers and needs to be recognisable as
 * neither.
 */
export const WATERMARK_ID_PREFIX = 'ms-wm-v';

export function watermarkId(version: number): string {
  if (!Number.isInteger(version) || version < 1) {
    throw new RangeError(`watermark version must be a positive integer, received ${String(version)}`);
  }
  return `${WATERMARK_ID_PREFIX}${String(version)}`;
}

/** The version a watermark identifier names, or `null` when it names none. */
export function watermarkVersionOf(id: string): number | null {
  if (!id.startsWith(WATERMARK_ID_PREFIX)) return null;
  const digits = id.slice(WATERMARK_ID_PREFIX.length);
  // `Number` would accept '1.5', ' 1' and '1e3'; the identifier is a version, not an expression.
  if (!/^[1-9][0-9]*$/.test(digits)) return null;
  return Number(digits);
}
