-- 0008 — Audit_Log (design §4.4).
--
-- Append-only, partitioned by month, minimum retention 365 days, email and API
-- key stored masked. Partition naming and the retention floor match
-- `domain/audit-log/partition.ts`; the masked formats match
-- `domain/audit-log/masking.ts`.

CREATE TABLE audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    event_type text NOT NULL,
    actor_id uuid,
    target_id uuid,
    -- Masked at the boundary: `***@domain.com` and `sk-***last4`.
    actor_email_masked text,
    api_key_masked text,
    before_value jsonb,
    after_value jsonb,
    event_time timestamptz NOT NULL DEFAULT now(),

    -- The partition key has to be part of the primary key.
    PRIMARY KEY (id, event_time),

    CONSTRAINT audit_log_event_type_present CHECK (char_length(event_type) BETWEEN 1 AND 64),
    CONSTRAINT audit_log_email_masked CHECK (
        actor_email_masked IS NULL
        OR actor_email_masked = '***'
        OR actor_email_masked ~ '^\*\*\*@[^@[:space:]]+$'
    ),
    CONSTRAINT audit_log_api_key_masked CHECK (
        api_key_masked IS NULL
        OR api_key_masked ~ '^sk-\*\*\*[A-Za-z0-9_-]{0,4}$'
    )
) PARTITION BY RANGE (event_time);

COMMENT ON TABLE audit_log IS
    'Design §4.4: append-only, monthly partitions, >= 365 day retention, PII masked.';

-- Append-only. DROP/DETACH of a whole partition is unaffected, so retention
-- pruning still works.
CREATE OR REPLACE FUNCTION audit_log_reject_mutation()
RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_log is append-only (design §4.4): % is not permitted', TG_OP
        USING ERRCODE = 'MS018';
END;
$$;

CREATE TRIGGER audit_log_no_update
    BEFORE UPDATE ON audit_log
    FOR EACH ROW
    EXECUTE FUNCTION audit_log_reject_mutation();

CREATE TRIGGER audit_log_no_delete
    BEFORE DELETE ON audit_log
    FOR EACH ROW
    EXECUTE FUNCTION audit_log_reject_mutation();

REVOKE UPDATE, DELETE, TRUNCATE ON audit_log FROM PUBLIC;

CREATE OR REPLACE FUNCTION audit_log_partition_name(p_month date)
RETURNS text
LANGUAGE sql IMMUTABLE AS $$
    SELECT 'audit_log_' || to_char(date_trunc('month', p_month::timestamp), 'YYYY_MM');
$$;

-- Idempotent: creating the partition for a month that already has one is a no-op,
-- so this is safe to call from an insert path or a scheduled job.
CREATE OR REPLACE FUNCTION audit_log_ensure_partition(p_month date)
RETURNS text
LANGUAGE plpgsql AS $$
DECLARE
    v_from date := date_trunc('month', p_month::timestamp)::date;
    v_to date := (date_trunc('month', p_month::timestamp) + interval '1 month')::date;
    v_name text := audit_log_partition_name(p_month);
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = v_name) THEN
        EXECUTE format(
            'CREATE TABLE %I PARTITION OF audit_log FOR VALUES FROM (%L) TO (%L)',
            v_name, v_from, v_to
        );
        EXECUTE format('REVOKE UPDATE, DELETE, TRUNCATE ON %I FROM PUBLIC', v_name);
    END IF;

    RETURN v_name;
END;
$$;

-- Partitions whose entire range has aged out of the retention window. Retention
-- below the design §4.4 floor of 365 days is a programming error, not a setting.
CREATE OR REPLACE FUNCTION audit_log_prunable_partitions(
    p_retain_days integer DEFAULT 365,
    p_now timestamptz DEFAULT now()
)
RETURNS TABLE (partition_name text, to_exclusive date)
LANGUAGE plpgsql STABLE AS $$
BEGIN
    IF p_retain_days < 365 THEN
        RAISE EXCEPTION
            'audit log retention must be at least 365 days (design §4.4), received %',
            p_retain_days
            USING ERRCODE = 'MS018';
    END IF;

    RETURN QUERY
    SELECT
        part.relname::text,
        ((to_date(right(part.relname, 7), 'YYYY_MM') + interval '1 month')::date)
    FROM pg_inherits i
    JOIN pg_class part ON part.oid = i.inhrelid
    JOIN pg_class parent ON parent.oid = i.inhparent
    WHERE parent.relname = 'audit_log'
      AND ((to_date(right(part.relname, 7), 'YYYY_MM') + interval '1 month')::date)
          <= (p_now - make_interval(days => p_retain_days))::date
    ORDER BY 1;
END;
$$;

-- Previous month through twelve months ahead, so inserts never land on a missing
-- partition before the scheduled job runs. No DEFAULT partition on purpose: a
-- missing month must fail loudly rather than silently pool into one table.
DO $$
DECLARE
    v_month date;
BEGIN
    FOR v_month IN
        SELECT generate_series(
            date_trunc('month', now()) - interval '1 month',
            date_trunc('month', now()) + interval '12 months',
            interval '1 month'
        )::date
    LOOP
        PERFORM audit_log_ensure_partition(v_month);
    END LOOP;
END;
$$;

CREATE INDEX audit_log_event_time_idx ON audit_log (event_time DESC);
CREATE INDEX audit_log_actor_idx ON audit_log (actor_id, event_time DESC);
CREATE INDEX audit_log_target_idx ON audit_log (target_id, event_time DESC);
CREATE INDEX audit_log_event_type_idx ON audit_log (event_type, event_time DESC);
